#!/usr/bin/env bash
# This script displays "Best School" 10 times using a while loop

counter=1
while [ "$counter" -le 10 ]  # using quotes for safety
do
  echo "Best School"
  ((counter++))  # increment the counter
done
