#!/usr/bin/env bash
# This script displays "Best School" 10 times using an until loop

counter=1
until [ "$counter" -gt 10 ]  # loop until counter is greater than 10
do
  echo "Best School"
  ((counter++))  # increment the counter
done
