#!/usr/bin/env bash
# This script loops from 1 to 10 and displays different messages based on the iteration
# - Displays "bad luck" for the 4th iteration (4 is considered unlucky in Chinese culture)
# - Displays "good luck" for the 8th iteration (8 is considered lucky in Chinese culture)
# - Displays "Best School" for all other iterations

counter=1
while [ "$counter" -le 10 ]
do
  if [ "$counter" -eq 4 ]
  then
    echo "bad luck"  # 4 is considered unlucky in Chinese culture
  elif [ "$counter" -eq 8 ]
  then
    echo "good luck"  # 8 is considered lucky in Chinese culture
  else
    echo "Best School"
  fi
  ((counter++))
done
