#!/usr/bin/env bash
# This script displays numbers from 1 to 20
# - Displays "bad luck from China" for the 4th iteration
# - Displays "bad luck from Japan" for the 9th iteration
# - Displays "bad luck from Italy" for the 17th iteration

counter=1
while [ "$counter" -le 20 ]
do
  case $counter in
    4)
      echo "$counter"
      echo "bad luck from China"  # Print bad luck message on a new line
      ;;
    9)
      echo "$counter"
      echo "bad luck from Japan"  # Print bad luck message on a new line
      ;;
    17)
      echo "$counter"
      echo "bad luck from Italy"  # Print bad luck message on a new line
      ;;
    *)
      echo "$counter"
      ;;
  esac
  ((counter++))
done
